### ISSUE TITLE
toggleProperty not exported from @ember/object

### ISSUE THREAD

**Issue by gustaff-weldon** [ember-codemods/ember-modules-codemod#108]
I have checked https://github.com/emberjs/rfcs/blob/master/text/0176-javascript-module-api.md#addendum-1---table-of-module-names-and-exports-by-global
and cannot find where [`toggleProperty`](https://www.emberjs.com/api/ember/3.5/classes/EmberObject/methods/toggleProperty?anchor=toggleProperty) was moved. 

It's not it `@ember/object` since Babel complains that `@ember/object does not have a toggleProperty export`.

I could not find a related issue on [Ember repo](https://github.com/emberjs/ember.js/issues?utf8=%E2%9C%93&q=toggleProperty). 
Since, the docs in the RFC say the table is generated from this codemod scrips, thus I'm creating issue here for now. I believe that if that issue is a valid one, not just an incomplete documentation, Ember code needs to be updated first.

I can create a ticket in a proper repo, if that issue is valid, please advise.

**Comment by snewcomer** [comment]
@gustaff-weldon This is a property on the Component [class](https://api.emberjs.com/ember/3.11/classes/Component/methods/toggleProperty?anchor=toggleProperty)

Is this what you were looking for?

**Comment by rwjblue** [comment]
Right, I don't believe that `toggleProperty` isn't a utility method on the `window.Ember` global at all (its an instance method) and therefore I don't think it would end up in the new module paths.

Closing for now, but happy to reopen if I've made a mistake...
